name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - junalmeida
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please consider sponsoring if you feel that this project is somehow useful to you.
        Bug reports for add-ons can be reported on the respective add-on repository.
