name: Question
description: Ask a question or a feature request
title: "[Question]: "
labels: ["question"]
assignees:
  - junalmeida
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time using this project. Please consider sponsoring if you feel that this project is somehow useful to you.
        Questions related to add-ons can be reported on the respective add-on repository.
