name: Meter Parser
version: 1.0.2.3
slug: meter-parser
description: Read meter needles and numbers from a camera snapshot.
url: https://github.com/junalmeida/homeassistant-addons/tree/main/meterparser
init: false
image: "ghcr.io/junalmeida/ha-meterparser-addon-{arch}"
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  cameras:
    - snapshot_url: http://192.168.100.153/snapshot.jpg
      name: Water Meter
      interval: 60 # seconds
schema:
  mqtt_url: "url?"
  cameras:
    - snapshot_url: str
      name: str
      interval: "int(1,600)"
      unit_of_measurement: "list(m³|kWh|ft³|L|mL|gal)?"
      device_class: "list(water|energy|gas)?"
      dials:
        - "str?"
      digits: "int(0,10)?"
      decimals: "int(0,3)?"
      ocr_space_key: str?
      ocr_gvision_key: str?
      dial_size: "int(0,300)?"
      first_aruco: "int?"
      second_aruco: "int?"
      reading_limit: "int?"
      force_ffmpeg: "bool?"
